# Generated by Django 3.1.1 on 2020-10-02 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createqmodel',
            name='schedule_quantity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='createqmodel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
